---
- name: Create facts directory
  ansible.builtin.file:
    path: /etc/ansible/facts.d
    state: directory
    mode: "0755"

- name: Create redis facts
  ansible.builtin.template:
    src: etc/ansible/facts.d/redis.fact.j2
    dest: /etc/ansible/facts.d/redis.fact
    mode: "0644"
